-- Create the inquiries table used by the ZENCE contact form and admin dashboard.
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  selected_service text not null,
  project_scope text not null,
  created_at timestamptz not null default now(),
  status text not null default 'New'
);

-- Optional: allow anonymous inserts from the frontend via the anon key.
-- If your Supabase project uses RLS, enable the policies below.
alter table public.inquiries enable row level security;

create policy if not exists "Allow public inserts" on public.inquiries
for insert
to anon
with check (true);

create policy if not exists "Allow public reads" on public.inquiries
for select
to anon
using (true);

create policy if not exists "Allow public updates" on public.inquiries
for update
to anon
using (true)
with check (true);

create policy if not exists "Allow public deletes" on public.inquiries
for delete
to anon
using (true);
